language: node_js

node_js:
  - stable

env:
  global:
    - SAUCE_USERNAME=angular-sorted-map
    - secure: "dykEOQVyZuMyAhvgsYsvMexAx5kmlnIKLv1x20G9gLp7/4K3EoOqJFHrcLymIlf4TcVwvH/vHmjux0vPAjlsp0zoTsZGA+6xLu1yNlqKjgWHns5sXZjX86OSbMvvzkAIAVko0y5K8/mPyS1kSUDpteI3JmhHWEwUUai8JZYSmOrspzxxSIPHOjCxR0ejR6A6dZBYKa9SVR2+pr671yRkE9oxdr8RG4kSHN0/16qFXohqV1hFa1BQAYKb9exHy9nGDr43j0yudrSje5KDMTtNGXn22VaGh4/NgWBZ8+BQ0tUsxztM++5NCougrAyV6cYfid/sahpDO5KRaWDeS7D1pwCJMg5TFP/x7kG8GgTpyClaMUU0P+mvr4B41tgydYpqSpwUxIUVrVE0eympDm3UheWvr1P3EYObAm/D6LHyqbu5nrc+JyEVjwRRhT7CvuAO2tmfrqhvvX9tpuVeN/sSAdCdIOIdZzsH3fAuRO3uQZsYXR1XO5vpS6YwI2KGHQKBGHq31kx6o8SVU8icaSgwYd7Ko/vmmnLmHAyqQ/qS3TeOv0LoRT3zvMCNF+10JzeuSJ3DglnfbvpUVWdJbNWDI7h6/UwA0mjJv/Uzybhbc65chy9kwDxdBcRfzke2DGaw1kXzQ+Ze8NzTcs5UZtv24vfpCmeJL/XZD2hpGwZcfWo="
  matrix:
    - SAUCE_BROWSER="Internet Explorer, 6, Windows XP"
    - SAUCE_BROWSER="Internet Explorer, 8, Windows XP"
    - SAUCE_BROWSER="Internet Explorer, latest, Windows 10"
    - SAUCE_BROWSER="MicrosoftEdge, latest, Windows 10"
    - SAUCE_BROWSER="Firefox, 4, Linux"
    - SAUCE_BROWSER="Firefox, 31, Linux"
    - SAUCE_BROWSER="Firefox, latest, Linux"
    - SAUCE_BROWSER="Chrome, 26, Linux"
    - SAUCE_BROWSER="Chrome, 31, Linux"
    - SAUCE_BROWSER="Chrome, latest, Linux"
    - SAUCE_BROWSER="Safari, 5, Windows 7"
    - SAUCE_BROWSER="Safari, 7, OS X 10.9"
    - SAUCE_BROWSER="Safari, 9, OS X 10.11"
    - SAUCE_BROWSER="Opera, 11, Windows 7"
    - SAUCE_BROWSER="Opera, 12, Windows 7"

cache:
  directories:
    - node_modules

deploy:
  provider: releases
  api_key:
    secure: joIAOh+WktWlPAkZa8UDgblYnkhwtwUSGdtuf90HfuxN7oyuSnz0qtAxLAs0mjzllUkNZ2xR4Mme62Csqr1Fk43EKdQioypNZmTORzdCpcPNlYkNSGa8KGJ1Haz2cWIjywBlvY5vCoJpL9a6fxt1z9VNlEsjwPdp0Kb4WGOljRuY8TbN0SF2ebAvaf42rPOB/4Odz1gCnu3fBEqx8808Frnn9h8yLDuDlOdk9CgJpri+urDui47+aNAi8qcdcOGvyy9z8w83DbxH8xN0irntWiFfJR9vcEt7gTQ6J3jJwWWmb6vwg2J85GuHAV/vmdODqb5O00jejlNkT8FDFs98KOlDpjhhWq5b6UX9EUOrZUlHF406nUN+wgrrI84z0jS0leUHAvPo3rupU6CnFvI+/DVwjzDVi+XYCF/57U3sZQCNlBqvKpkP7YrgVLWQn3qbMt/BDSMlENlJLstJtelmwckp1K63Lwu7fprwMvqx7bfRoty8tyK3sQwZvF4p18ybz39Q7w9VHYxNzilMK1Ck0mUjq8uV41sJ3UrG6CUX5QGSLQd1licZPVnAhWLfOu41XRo0io8Qeaq2eWuZG3RGT49BhI9x+BYDsfuB3UC4zubYr3rtFrmjah9dXK9Y8ZocB3xrO4JGbgqMrO35N/XdnDErlugHMqoKL4aKlPjv/d0=
  file:
    - lib/angular-sorted-map.min.js
    - lib/angular-sorted-map.min.js.map
  skip_cleanup: true
  on:
    tags: true
